### ISSUE TITLE
remove template cache on package upgrades

### ISSUE THREAD

**Issue by ghost** [eduvpn-debian/packaging#13]
As used by the RPM spec files:

## vpn-admin-portal
``rm -rf %{_localstatedir}/lib/%{name}/*/tpl/* >/dev/null 2>/dev/null || :``

## vpn-user-portal
``rm -rf %{_localstatedir}/lib/%{name}/*/tpl/* >/dev/null 2>/dev/null || :``

## php-saml-ds
``rm -rf %{_localstatedir}/lib/%{name}/tpl/* >/dev/null 2>/dev/null || :``

**NOTE** the `php-saml-ds` case is slightly different!

**Comment by gijzelaerr** [comment]
@fkooman is there an easy way to trigger the generation of the template caches so I can test if this is working?

**Comment by ghost** [comment]
First use of the portal(s) will fill the template cache.

**Comment by gijzelaerr** [comment]
implemented
