### ISSUE TITLE
Stretch 9.1 i386 (32bit) install package fails

### ISSUE THREAD

**Issue by efef** [eduvpn-debian/packaging#16]
When running 32bit debian Stretch, the package can't be installed

apt-update gives error:
All packages are up to date.
N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'https://repo.eduvpn.org/debian stretch InRelease' doesn't support architecture 'i386'

 apt install eduvpn-client
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package eduvpn-client

**Comment by gijzelaerr** [comment]
packages are now also i386
