### ISSUE TITLE
Stretch 9.1 amd64 GTK-warning GUI images not loading

### ISSUE THREAD

**Issue by StefanGrimminck** [eduvpn-debian/packaging#17]
When running eduvpn the images in the GUI won't load.
followed by the following warning:

`Gtk-WARNING **: Could not load image '../icons/hicolor/256x256/apps/eduvpn-client.png': Failed to open file '/usr/bin/../share/eduvpn/../icons/hicolor/256x256/apps/eduvpn-client.png': No such file or directory`

**Comment by gijzelaerr** [comment]
thanks for reporting, this is an easy fix, will be in next release.

**Comment by gijzelaerr** [comment]
moved to python-eduvpn-client repo
