### ISSUE TITLE
package updates

### ISSUE THREAD

**Issue by ghost** [eduvpn-debian/packaging#18]
- [x] php-saml-ds.spec:Version:    1.0.6 (also remove templates)
- [x] vpn-admin-portal.spec:Version:    1.1.6 (also remove templates)
- [x] vpn-user-portal.spec:Version:    1.0.6 (also remove templates)
- [x] vpn-lib-common.spec:Version:    1.0.3
- [x] php-fkooman-secookie.spec:Version:        2.0.0
- [x] php-fkooman-yubitwee.spec:Version:        1.1.0
- [x] php-fkooman-oauth2-client: Version:     5.0.1
The `php-fkooman-yubitwee` package drops the `php-libsodium` dependency, but gets two new ones:
```
BuildRequires:  php-composer(paragonie/random_compat)
BuildRequires:  php-composer(symfony/polyfill-php56)
```

**Comment by ghost** [comment]
- [x]  php-oauth2-server: Version 1.1.0 

New runtime/build dependencies:
php-composer(paragonie/random_compat)
php-composer(symfony/polyfill-php56)

On PHP < 7.2 it depends on php-libsodium, on PHP > 7.2 it depends on php-sodium.

**Comment by ghost** [comment]
- [x]  vpn-lib-common: 1.0.4  Also has changed dependencies: https://github.com/eduvpn/vpn-lib-common/compare/1.0.3...1.0.4#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780

**Comment by gijzelaerr** [comment]
@fkooman the `vpn-lib-common` diff link doesn't seem to work (anymore).

**Comment by gijzelaerr** [comment]
link to diff doesn't work anymore, i guess it is this one https://github.com/eduvpn/vpn-lib-common/compare/1.0.3...1.0.4

**Comment by ghost** [comment]
GitHub broke the link, funny. Click [here](https://github.com/eduvpn/vpn-lib-common/compare/1.0.3...1.0.4#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780)

**Comment by gijzelaerr** [comment]
all packages have been updated.
