### ISSUE TITLE
use public https URL

### ISSUE THREAD

**Issue by ghost** [eduvpn-debian/packaging#20]
https://github.com/eduvpn-debian/packaging/blob/883d3940c151560a91194899edfc66612abf1035/build_all.sh#L17

**Comment by gijzelaerr** [comment]
but then you can't push updates on new upstream release.

**Comment by ghost** [comment]
building and updating are different things. So for building packages you don't need to push anything I assume. On our build server we don't have Git write access to any repository.

**Comment by ghost** [comment]
Maybe you can describe all steps from a clean Debian 9 VM. For example: create GPG key, set this and this environment variable, install package X, Y, Z and then run `./build_all.sh`.

**Comment by ghost** [comment]
e.g. https://github.com/eduvpn/documentation/tree/master/release

**Comment by gijzelaerr** [comment]
about if building and updating are different things, we could make that different things, but then we have 2 different workflows. I'm not really keen of solving all use cases. 

I think we should not try to create a debian packaging tools too much, there are already debian packaging tools. I could create some scripts that automate some things, but to solve all use cases would be just replicating the behaviour of the existing tools.

**Comment by gijzelaerr** [comment]
Now I think about it, the documented workflow should work for a clean debian install. The scripts are just an example on how it can be done. I don't like to fix a workflow for somebody, unless it is well determined where it is going to be used for. You analyse the script at the moment from various use cases, which I think we should not do. We don't want to automate the packaging for non maintainers and maintainers at the some time.

**Comment by gijzelaerr** [comment]
from a discussion with Rogier it became clear that the documentation and scripts should be written for a non-maintainer, somebody who just wants to build the packages and not publish them to the eduVPN repository.

**Comment by gijzelaerr** [comment]
script is using public URL now.
