### ISSUE TITLE
there is a pointer to your key somewhere?

### ISSUE THREAD

**Issue by ghost** [eduvpn-debian/packaging#23]
```
Now running lintian...
warning: the authors of lintian do not recommend running it with root privileges!
W: easy-rsa source: changelog-should-mention-nmu
W: easy-rsa source: source-nmu-has-incorrect-version-number 3.0.3-1
W: easy-rsa source: ancient-standards-version 3.9.5 (current is 3.9.8)
W: easy-rsa: extra-license-file usr/share/doc/easy-rsa/COPYING.md
W: easy-rsa: extra-license-file usr/share/doc/easy-rsa/gpl-2.0.txt.gz
Finished running lintian.
Now signing changes and any dsc files...
 signfile dsc easy-rsa_3.0.3-1.dsc Gijs Molenaar (launchpad ppa build key) <gijs@pythonic.nl>
gpg: skipped "Gijs Molenaar (launchpad ppa build key) <gijs@pythonic.nl>": No secret key
gpg: /tmp/debsign.CNQwSDel/easy-rsa_3.0.3-1.dsc: clear-sign failed: No secret key
debsign: gpg error occurred!  Aborting....
debuild: fatal error at line 1045:
running debsign failed
gbp:error: 'debuild -i -I' failed: it exited with 29
```

I have this file `vars` that I `source` before running `./build_all.sh` as root:
```
export DEBEMAIL=debian@eduvpn.nl
export DEBFULLNAME=debian@eduvpn.nl
export DEB_BUILD_OPTIONS="parallel=32"
```

There is a GPG key with ID `debian@eduvpn.nl`:

```
root@debian:/home/debian/packaging# gpg -K
/root/.gnupg/pubring.kbx
------------------------
sec   rsa2048 2017-10-02 [SC] [expires: 2019-10-02]
      25A18A8B967C2C6F72B458B1B2981E328A9263B2
uid           [ultimate] debian@eduvpn.nl
ssb   rsa2048 2017-10-02 [E]

root@debian:/home/debian/packaging# 
```

**Comment by gijzelaerr** [comment]
this is in the changelog. The packages need to have a changelog entry signed with the key we want to use.

**Comment by gijzelaerr** [comment]
for example here:

https://github.com/eduvpn-debian/python-eduvpn-client/blob/master/debian/changelog#L5

The changelog entry is updated using the environment variables when running for example `dch`

**Comment by ghost** [comment]
Is this relevant for creating a build? We don't have your private key, so this will never work?

**Comment by gijzelaerr** [comment]
it is relevant for signing everything and publishing. Building should work. Maybe the script should be modified to continue after a failed sign.

If you want to sign with your own key you need to update the changelog entry.

**Comment by ghost** [comment]
Maybe the script could be modified to add an entry to the changelog so it will work with the new key.

**Comment by gijzelaerr** [comment]
I don't agree. Then you make a new binary release for every build. I think we should not try to automate this too much. We could prepare everything for the final production environment (make changelog entries with eduvpn key, sign all source and binary packages), and assume that is the workflow from now on.

**Comment by gijzelaerr** [comment]
signing of (source) packages is disabled now.
