### ISSUE TITLE
make `build_all.sh` work without requiring root privileges

### ISSUE THREAD

**Issue by ghost** [eduvpn-debian/packaging#24]
https://github.com/eduvpn-debian/packaging/blob/883d3940c151560a91194899edfc66612abf1035/build_all.sh#L4

**Comment by gijzelaerr** [comment]
https://github.com/eduvpn-debian/packaging/blob/master/build_all.sh#L23

maybe you would formulate it different, but it requires sudo access.

**Comment by ghost** [comment]
I think the Debian tooling itself warns that you should not run it as root. So maybe you can split out the privileged operations, e.g. installing required packages first manually, and only normal user stuff in the build script.

**Comment by gijzelaerr** [comment]
i don't know what the requires packages are, that is determined during a build. And you don't want to have non dependencies of other packages installed during packaging per se, so I don't think it is a good idea.

I think we first need to decide who is actually going to use these scripts, and in what kind of environment. These scripts were intended as an example and should be customised to the repository maintainer needs. If *I* am the repository maintainer, then I prefer to leave it the way it is now.

**Comment by gijzelaerr** [comment]
so if we modify this script for a non-maintainer, you propose:

* have a script to install all build dependencies (`install_build_deps.sh`) which you should run as root

* have a script that actually builds the packages (`build_packages.sh`), run as a normal user.

In my opinion this just makes things more complex. Building packages is not really a normal user activity, and it is quite probably a user would have/need root access to the build machine to install dependencies. I would suggest a script saying some actions require sudo just makes it simpler. But in the end I think this is just bikeshedding so if you think this is very important than i'm fine with this approach.

**Comment by gijzelaerr** [comment]
ok so since for now I'm the only one using this scripts and I like it the way it is i''m closing this isue.
