### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by twizted** [eduvpn-debian/packaging#36]
Some of the packages seem to be missing specifications for some of the dependencies, which in the end leads to the deployment failing if the portals/server api and the VPN node deployment isn't done on the same machine. Wasn't sure if you would prefer to have those all listed in one issue ticket or separated, decided for the former to produce less clutter.

Package `vpn-server-node` should have `php-symfony-phpunit-bridge` marked as a dependency, otherwise it later loudly fails while trying to include `/usr/share/php/Symfony/Bridge/PhpUnit/autoload.php` in runtime.

Package `vpn-server-api` should have `openvpn` marked as a dependency, otherwise it fails when trying to generate the `tls-auth` shared secret file as it's using `openvpn` for that.

**Comment by gijzelaerr** [comment]
* [x] add `php-symfony-phpunit-bridge` to `vpn-server-node`
 * [x] add `openvpn` dependency to  `vpn-server-api`

**Comment by gijzelaerr** [comment]
done!
