### ISSUE TITLE
build_all does not work

### ISSUE THREAD

**Issue by ghost** [eduvpn-debian/packaging#40]
`MAINT=false`

```
gbp:info: Creating otp_2.4.0.orig.tar.gz from 'upstream/2.4.0'
 dpkg-buildpackage -rfakeroot -us -uc -i -I
dpkg-buildpackage: info: source package otp
dpkg-buildpackage: info: source version 2.4.0-3
dpkg-buildpackage: info: source distribution stable
dpkg-buildpackage: info: source changed by Gijs Molenaar (launchpad ppa build key) <gijs@pythonic.nl>
 dpkg-source -i -I --before-build otp
dpkg-buildpackage: info: host architecture amd64
dpkg-checkbuilddeps: error: Unmet build dependencies: php-paragonie-constant-time-encoding php-paragonie-random-compat
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)
debuild: fatal error at line 1116:
dpkg-buildpackage -rfakeroot -us -uc -i -I failed
gbp:error: 'debuild -i -I -us -uc' failed: it exited with 29
```

**Comment by gijzelaerr** [comment]
did the `mk-build-deps -i` work? If not you probably don't have eduvpn repository added to the build system.

**Comment by ghost** [comment]
Yeah, but the whole point of this script is to be able to build everything from scratch without existing repository, i.e. bootstrap the repo...

**Comment by gijzelaerr** [comment]
nope, it depends on the repository. If you want to do what you describe you need to create your own repository, add the packages to that repository and point your system or chroot build environment to use that. But this requires a bit more tweaking and is fragile to automate in a script. As said before, these scripts are just an example of how it could be and this is what I use for updating the packages.

**Comment by gijzelaerr** [comment]
I do the local repo for an other project:

https://github.com/kernsuite/packaging

but this setup is quite project/system specific. I prefer not to make these scripts to opinionated. It is probably best to have a dedicated configured machine somewhere to do the packaging.

**Comment by ghost** [comment]
What I don't understand is why this is so hard. Your script could create a local repository and add the dependencies one by one and then use that to build the rest. On CentOS I use a little wrapper around mock (mockchain) that does this.

**Comment by gijzelaerr** [comment]
I think we disagree what this script is and should do. But feel free to customise it to your needs. The easiest is just to add the remote repo, then it builds.

What you could do is run `apt-ftparchive packages . > Packages` in the folder of your deb packages every time you build a new package. Then add that archive to your local setup
```
deb [trusted=yes] file:///path/to/deb/folder ./"
```
But note that `apt-ftparchive` operates recursively, so probably better to put all deb files in a different folder. An other way is to build using a chroot environment, but then you first need to initialise and configure the chroot environment. Again something too fragile to script in my opinion, better to set up manually.

**Comment by ghost** [comment]
Wrote my own: https://github.com/fkooman/eduvpn-debian
