### ISSUE TITLE
fix httpd config snippets (php-fpm socket)

### ISSUE THREAD

**Issue by ghost** [eduvpn-debian/packaging#7]
```

                SetHandler "proxy:unix:/run/php-fpm/www.sock|fcgi://localhost"
                # Debian
#SetHandler "proxy:unix:/run/php/php7.0-fpm.sock|fcgi://localhost"
```

so update the SetHandler in all of them! 

vpn-user-portal
vpn-server-api
vpn-admin-portal
php-saml-ds

**Comment by gijzelaerr** [comment]
fixed, packages uploaded soon.

**Comment by ghost** [comment]
actually, this is no longer needed. If you take the httpd snippets from https://github.com/eduvpn/documentation/tree/master/rpm there the php-fpm stuff is no longer set. In Debian this is actually configured in `/etc/apache2/conf-available/php7.0-fpm.conf` globally. So no need to do this again in httpd snippets.
