### ISSUE TITLE
QR code does not work

### ISSUE THREAD

**Issue by ghost** [eduvpn-debian/packaging#9]
- `php-bacon-qr-code` misses dependency on `php-gd`;
- install path of `php-bacon-qr-code` is wrong, should be `/usr/share/php/BaconQrCode` and not `/usr/share/php/BaconQrCode/BaconQrCode`;
- `vpn-user-portal` misses BaconQrCode autoloader

**Comment by gijzelaerr** [comment]
fixed and uploaded.

https://github.com/eduvpn-debian/vpn-user-portal/commit/b8e1753507b68c417ae3cbab7a779e277e0c55c3

https://github.com/eduvpn-debian/baconqrcode/commit/3017b362863bca3c60e35c9fd07e62141156ec9e
